import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { Card, CardContent } from "@/components/ui/card";
import { AlertTriangle, CheckCircle, Mail } from "lucide-react";

const Disclaimer = () => {
  return (
    <div className="min-h-screen flex flex-col bg-background">
      <Header />

      <main className="flex-1">
        <section className="border-b border-border bg-gradient-to-b from-background to-accent/5 py-16 md:py-24">
          <div className="container max-w-4xl">
            <div className="flex flex-col items-center text-center gap-4">
              <div className="flex items-center justify-center w-16 h-16 rounded-2xl bg-accent mb-2">
                <AlertTriangle className="w-8 h-8 text-accent-foreground" />
              </div>
              <h1 className="text-4xl md:text-5xl lg:text-6xl font-bold tracking-tight text-foreground">
                Disclaimer
              </h1>
              <p className="text-xl md:text-2xl text-muted-foreground max-w-2xl">
                The information, services, and tools provided by CorrectNow are offered for general informational and productivity purposes only. By using CorrectNow, you acknowledge and agree to the terms of this Disclaimer.
              </p>
            </div>
          </div>
        </section>

        <section className="py-16 md:py-20">
          <div className="container max-w-4xl space-y-6">
            <Card>
              <CardContent className="p-8 md:p-10 space-y-4">
                <h2 className="text-2xl font-bold text-foreground">1. No Professional Advice</h2>
                <p className="text-muted-foreground text-lg">CorrectNow is an AI-powered proofreading and writing assistance tool.</p>
                <p className="text-muted-foreground text-lg">It does not provide:</p>
                <ul className="space-y-2 text-muted-foreground text-lg">
                  <li className="flex items-start gap-2">
                    <CheckCircle className="w-5 h-5 text-accent shrink-0 mt-0.5" />
                    <span>Legal advice</span>
                  </li>
                  <li className="flex items-start gap-2">
                    <CheckCircle className="w-5 h-5 text-accent shrink-0 mt-0.5" />
                    <span>Academic or examination advice</span>
                  </li>
                  <li className="flex items-start gap-2">
                    <CheckCircle className="w-5 h-5 text-accent shrink-0 mt-0.5" />
                    <span>Medical advice</span>
                  </li>
                  <li className="flex items-start gap-2">
                    <CheckCircle className="w-5 h-5 text-accent shrink-0 mt-0.5" />
                    <span>Financial or professional consulting advice</span>
                  </li>
                </ul>
                <p className="text-muted-foreground text-lg">
                  Any suggestions, corrections, rewrites, or outputs generated by CorrectNow are not a substitute for professional judgment. You should consult a qualified professional where appropriate.
                </p>
              </CardContent>
            </Card>

            <Card>
              <CardContent className="p-8 md:p-10 space-y-4">
                <h2 className="text-2xl font-bold text-foreground">2. AI-Generated Content Disclaimer</h2>
                <p className="text-muted-foreground text-lg">
                  CorrectNow uses artificial intelligence and machine learning to generate suggestions and content.
                </p>
                <p className="text-muted-foreground text-lg">You acknowledge and agree that:</p>
                <ul className="space-y-2 text-muted-foreground text-lg">
                  <li className="flex items-start gap-2">
                    <CheckCircle className="w-5 h-5 text-accent shrink-0 mt-0.5" />
                    <span>AI outputs may be inaccurate, incomplete, or inappropriate</span>
                  </li>
                  <li className="flex items-start gap-2">
                    <CheckCircle className="w-5 h-5 text-accent shrink-0 mt-0.5" />
                    <span>Outputs may contain errors, biases, or outdated information</span>
                  </li>
                  <li className="flex items-start gap-2">
                    <CheckCircle className="w-5 h-5 text-accent shrink-0 mt-0.5" />
                    <span>Similar inputs may produce similar outputs for different users</span>
                  </li>
                  <li className="flex items-start gap-2">
                    <CheckCircle className="w-5 h-5 text-accent shrink-0 mt-0.5" />
                    <span>AI-generated content should be reviewed and verified by you before use</span>
                  </li>
                </ul>
                <p className="text-muted-foreground text-lg">
                  You are solely responsible for how you use, publish, submit, or rely on any output generated by CorrectNow.
                </p>
              </CardContent>
            </Card>

            <Card>
              <CardContent className="p-8 md:p-10 space-y-4">
                <h2 className="text-2xl font-bold text-foreground">3. No Guarantee of Accuracy or Results</h2>
                <p className="text-muted-foreground text-lg">CorrectNow does not guarantee:</p>
                <ul className="space-y-2 text-muted-foreground text-lg">
                  <li className="flex items-start gap-2">
                    <CheckCircle className="w-5 h-5 text-accent shrink-0 mt-0.5" />
                    <span>100% grammatical correctness</span>
                  </li>
                  <li className="flex items-start gap-2">
                    <CheckCircle className="w-5 h-5 text-accent shrink-0 mt-0.5" />
                    <span>Error-free writing</span>
                  </li>
                  <li className="flex items-start gap-2">
                    <CheckCircle className="w-5 h-5 text-accent shrink-0 mt-0.5" />
                    <span>Acceptance by institutions, employers, publishers, or platforms</span>
                  </li>
                  <li className="flex items-start gap-2">
                    <CheckCircle className="w-5 h-5 text-accent shrink-0 mt-0.5" />
                    <span>Improved grades, job outcomes, or business results</span>
                  </li>
                </ul>
                <p className="text-muted-foreground text-lg">
                  Language is complex and contextual, and results may vary depending on usage, content type, and user intent.
                </p>
              </CardContent>
            </Card>

            <Card>
              <CardContent className="p-8 md:p-10 space-y-4">
                <h2 className="text-2xl font-bold text-foreground">4. User Responsibility</h2>
                <p className="text-muted-foreground text-lg">By using CorrectNow, you agree that:</p>
                <ul className="space-y-2 text-muted-foreground text-lg">
                  <li className="flex items-start gap-2">
                    <CheckCircle className="w-5 h-5 text-accent shrink-0 mt-0.5" />
                    <span>You are fully responsible for your content and decisions</span>
                  </li>
                  <li className="flex items-start gap-2">
                    <CheckCircle className="w-5 h-5 text-accent shrink-0 mt-0.5" />
                    <span>You will review and validate all suggestions before use</span>
                  </li>
                  <li className="flex items-start gap-2">
                    <CheckCircle className="w-5 h-5 text-accent shrink-0 mt-0.5" />
                    <span>You will ensure compliance with applicable laws, academic policies, and professional standards</span>
                  </li>
                </ul>
                <p className="text-muted-foreground text-lg">CorrectNow is a support tool, not a decision-maker.</p>
              </CardContent>
            </Card>

            <Card>
              <CardContent className="p-8 md:p-10 space-y-4">
                <h2 className="text-2xl font-bold text-foreground">5. No Liability for Damages</h2>
                <p className="text-muted-foreground text-lg">
                  To the fullest extent permitted by law, CorrectNow shall not be liable for:
                </p>
                <ul className="space-y-2 text-muted-foreground text-lg">
                  <li className="flex items-start gap-2">
                    <CheckCircle className="w-5 h-5 text-accent shrink-0 mt-0.5" />
                    <span>Direct or indirect losses</span>
                  </li>
                  <li className="flex items-start gap-2">
                    <CheckCircle className="w-5 h-5 text-accent shrink-0 mt-0.5" />
                    <span>Loss of data, reputation, or revenue</span>
                  </li>
                  <li className="flex items-start gap-2">
                    <CheckCircle className="w-5 h-5 text-accent shrink-0 mt-0.5" />
                    <span>Academic, legal, or professional consequences</span>
                  </li>
                  <li className="flex items-start gap-2">
                    <CheckCircle className="w-5 h-5 text-accent shrink-0 mt-0.5" />
                    <span>Claims arising from reliance on AI-generated content</span>
                  </li>
                </ul>
                <p className="text-muted-foreground text-lg">Your use of the Services is entirely at your own risk.</p>
              </CardContent>
            </Card>

            <Card>
              <CardContent className="p-8 md:p-10 space-y-4">
                <h2 className="text-2xl font-bold text-foreground">6. External Links &amp; Third-Party Content</h2>
                <p className="text-muted-foreground text-lg">
                  CorrectNow may include links to third-party websites, tools, or services.
                </p>
                <ul className="space-y-2 text-muted-foreground text-lg">
                  <li className="flex items-start gap-2">
                    <CheckCircle className="w-5 h-5 text-accent shrink-0 mt-0.5" />
                    <span>We do not control or endorse third-party content</span>
                  </li>
                  <li className="flex items-start gap-2">
                    <CheckCircle className="w-5 h-5 text-accent shrink-0 mt-0.5" />
                    <span>We are not responsible for their accuracy, availability, or policies</span>
                  </li>
                  <li className="flex items-start gap-2">
                    <CheckCircle className="w-5 h-5 text-accent shrink-0 mt-0.5" />
                    <span>Use of third-party services is at your own discretion</span>
                  </li>
                </ul>
              </CardContent>
            </Card>

            <Card>
              <CardContent className="p-8 md:p-10 space-y-4">
                <h2 className="text-2xl font-bold text-foreground">7. Availability &amp; Technical Limitations</h2>
                <p className="text-muted-foreground text-lg">
                  CorrectNow is provided on an “as is” and “as available” basis.
                </p>
                <p className="text-muted-foreground text-lg">We do not guarantee:</p>
                <ul className="space-y-2 text-muted-foreground text-lg">
                  <li className="flex items-start gap-2">
                    <CheckCircle className="w-5 h-5 text-accent shrink-0 mt-0.5" />
                    <span>Uninterrupted service</span>
                  </li>
                  <li className="flex items-start gap-2">
                    <CheckCircle className="w-5 h-5 text-accent shrink-0 mt-0.5" />
                    <span>Error-free operation</span>
                  </li>
                  <li className="flex items-start gap-2">
                    <CheckCircle className="w-5 h-5 text-accent shrink-0 mt-0.5" />
                    <span>Compatibility with all devices or software</span>
                  </li>
                </ul>
                <p className="text-muted-foreground text-lg">
                  Service availability may be affected by maintenance, updates, or external factors.
                </p>
              </CardContent>
            </Card>

            <Card>
              <CardContent className="p-8 md:p-10 space-y-4">
                <h2 className="text-2xl font-bold text-foreground">8. Jurisdictional Limitations</h2>
                <p className="text-muted-foreground text-lg">
                  Some jurisdictions do not allow certain disclaimers or limitations of liability. Where such laws apply, this Disclaimer will apply to the maximum extent permitted by law.
                </p>
              </CardContent>
            </Card>

            <Card>
              <CardContent className="p-8 md:p-10 space-y-4">
                <h2 className="text-2xl font-bold text-foreground">9. Changes to This Disclaimer</h2>
                <p className="text-muted-foreground text-lg">We may update this Disclaimer from time to time.</p>
                <p className="text-muted-foreground text-lg">
                  Continued use of CorrectNow after updates constitutes acceptance of the revised Disclaimer.
                </p>
              </CardContent>
            </Card>

            <Card>
              <CardContent className="p-8 md:p-10 space-y-4">
                <h2 className="text-2xl font-bold text-foreground">10. Contact Information</h2>
                <p className="text-muted-foreground text-lg">If you have questions about this Disclaimer, contact us at:</p>
                <div className="flex items-center gap-2 text-lg font-semibold text-foreground">
                  <Mail className="w-5 h-5 text-accent" />
                  <span>📧 info@correctnow.app</span>
                </div>
              </CardContent>
            </Card>
          </div>
        </section>
      </main>

      <Footer />
    </div>
  );
};

export default Disclaimer;
